@php
$fr=$client->language==='fr';
$labels=$fr?['quote'=>'Devis','invoice'=>'Factures','contract'=>'Contrats','credit_note'=>'Avoirs']:['quote'=>'Quotes','invoice'=>'Invoices','contract'=>'Contracts','credit_note'=>'Credit notes'];
$statuses=$fr?['draft'=>'Brouillon','issued'=>'Émis','accepted'=>'Accepté','declined'=>'Refusé','signed'=>'Signé','paid'=>'Payée','partially_paid'=>'Paiement partiel','overdue'=>'En retard','credited'=>'Créditée']:['issued'=>'Issued','accepted'=>'Accepted','declined'=>'Declined','signed'=>'Signed','paid'=>'Paid','partially_paid'=>'Partially paid','overdue'=>'Overdue','credited'=>'Credited'];
$stages=$fr?['new'=>'Nouvelle demande','contacted'=>'Contact établi','quote_sent'=>'Devis envoyé','accepted'=>'Accepté','in_progress'=>'En cours','completed'=>'Terminé','lost'=>'Clôturé']: \App\Services\SalesPipeline::STAGES;
@endphp
<!doctype html><html lang="{{ $fr?'fr':'en' }}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="referrer" content="no-referrer"><title>{{ $fr?'Espace client':'Client portal' }} · {{ $company->legal_name }}</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f6f7fb;color:#182139;font:15px/1.6 system-ui,sans-serif}main,header{max-width:1100px;margin:auto;padding:24px}header{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #dfe3ed}.brand{font-weight:750;letter-spacing:-.03em}h1{font-size:clamp(25px,4vw,38px);letter-spacing:-.04em;margin:10px 0}h2{font-size:21px;letter-spacing:-.02em}.muted{color:#65708a}button,.button{display:inline-block;border:0;border-radius:9px;padding:10px 15px;background:#353acc;color:#fff;text-decoration:none;font:inherit;cursor:pointer}.secondary{background:#e9ecf7;color:#293260}.cards{display:flex;flex-wrap:wrap;gap:14px}.card{padding:20px;background:white;border:1px solid #dfe3ed;border-radius:14px;min-width:190px;flex:1}.amount{font-size:26px;font-weight:750}.table-wrap{overflow:auto;background:#fff;border:1px solid #dfe3ed;border-radius:14px}table{border-collapse:collapse;width:100%;min-width:650px}th,td{padding:15px;text-align:left;border-bottom:1px solid #e8ebf2}th{font-size:12px;text-transform:uppercase;color:#65708a}tr:last-child td{border:0}.badge{display:inline-block;background:#edf0fa;padding:3px 9px;border-radius:20px;font-size:12px}.accept{padding:16px;margin-top:12px;background:#fff;border:1px solid #dfe3ed;border-radius:12px}.accept label{display:block;margin:12px 0}.notice{border-radius:12px;background:#e3f4ea;padding:16px}.error{background:#ffebe9}.empty{padding:20px;color:#65708a}footer{margin:32px 0;color:#65708a;font-size:13px}section{margin-top:30px}@media(max-width:600px){main,header{padding:16px}.card{min-width:140px}header .brand{max-width:65%}}
</style></head><body>
<header><span class="brand">{{ $company->legal_name ?: 'Ayoub · Studio' }}</span><form method="post" action="{{ route('portal.leave') }}">@csrf<button class="secondary">{{ $fr?'Quitter':'Sign out' }}</button></form></header>
<main><div class="muted">{{ $fr?'Votre espace client':'Your client portal' }}</div><h1>{{ $client->display_name }}</h1><p class="muted">{{ $fr?'Vos projets, documents et paiements réunis au même endroit.':'Your projects, documents and payments in one place.' }}</p>
@if(session('portal_success'))<p class="notice">{{ $fr?'Devis accepté. Votre contact a été informé.':'Quote accepted. Your project contact has been notified.' }}</p>@endif
@if($errors->any())<div class="notice error">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
<div class="cards">@forelse($balances as $currency=>$balance)<div class="card"><div class="muted">{{ $fr?'Solde à payer':'Outstanding balance' }} · {{ $currency }}</div><div class="amount">{{ \App\Support\Money::decimal($balance) }}</div></div>@empty<div class="card"><div class="muted">{{ $fr?'Paiements':'Payments' }}</div><strong>{{ $fr?'Aucune facture en cours':'No issued invoices yet' }}</strong></div>@endforelse</div>
@if($projects->isNotEmpty())<section><h2>{{ $fr?'Vos projets':'Your projects' }}</h2><div class="cards">@foreach($projects as $project)<div class="card"><strong>{{ $project->service ?: ($fr?'Projet':'Project') }}</strong><p><span class="badge">{{ $stages[$project->status]??$project->status }}</span></p></div>@endforeach</div></section>@endif
@foreach($labels as $type=>$label)
<section><h2>{{ $label }}</h2><div class="table-wrap">@if($documents->where('type',$type)->isEmpty())<p class="empty">{{ $fr?'Aucun document pour le moment.':'No documents yet.' }}</p>@else<table><thead><tr><th>{{ $fr?'Document':'Document' }}</th><th>{{ $fr?'Statut':'Status' }}</th><th>{{ $fr?'Montant':'Amount' }}</th><th>{{ $fr?'Échéance / validité':'Due / valid until' }}</th><th>PDF</th></tr></thead><tbody>
@foreach($documents->where('type',$type) as $document)<tr><td><strong>N°{{ $document->number }}</strong><div class="muted">{{ $document->title }}</div>@if($document->source)<div class="muted">{{ $fr?'Lié au document':'Linked document' }} N°{{ $document->source->number }}</div>@endif @if($document->period_start)<div class="muted">{{ $document->period_start->format('d/m/Y') }} – {{ $document->period_end->format('d/m/Y') }}</div>@endif</td><td><span class="badge">{{ $statuses[$document->display_status]??$document->display_status }}</span></td><td>{{ $document->display_total }}@if($type==='invoice')<div class="muted">{{ $fr?'Payé':'Paid' }} : {{ \App\Support\Money::decimal($document->paidAmount()) }} {{ $document->currency }}</div><div class="muted">{{ $fr?'Restant':'Remaining' }} : {{ \App\Support\Money::decimal($document->balanceAmount()) }} {{ $document->currency }}</div>@endif</td><td>{{ $document->due_on?->format('d/m/Y')??'—' }}</td><td><a class="button secondary" href="{{ route('portal.pdf',$document->id) }}" target="_blank" rel="noreferrer">{{ $fr?'Voir le PDF':'View PDF' }}</a></td></tr>@endforeach
</tbody></table>@endif</div>
@if($type==='quote')@foreach($documents->where('type','quote')->where('status','issued') as $quote)@if(!$quote->due_on || $quote->due_on->toDateString() >= now('Africa/Casablanca')->toDateString())<form class="accept" method="post" action="{{ route('portal.accept',$quote->id) }}">@csrf<strong>{{ $fr?'Accepter le devis':'Accept quote' }} N°{{ $quote->number }}</strong><p class="muted">{{ $fr?'Consultez le PDF avant de confirmer. Cette action enregistre votre accord sur ce devis.':'Review the PDF before confirming. This records your acceptance of this quote.' }}</p><label><input type="checkbox" name="agreement" value="1" required> {{ $fr?'J’ai lu et j’accepte les prestations, prix et conditions de ce devis.':'I have read and accept the services, prices and terms of this quote.' }}</label><button>{{ $fr?'Confirmer mon accord':'Confirm acceptance' }}</button></form>@endif @endforeach @endif
</section>@endforeach
<footer>{{ $fr?'Pour toute question concernant votre projet ou un paiement, contactez':'For questions about your project or a payment, contact' }} {{ $company->email ?: $company->phone ?: $company->legal_name }}.</footer>
</main></body></html>
